CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    user_uuid VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL CHECK (char_length(password) > 5),
    username VARCHAR(25) NOT NULL UNIQUE
);

-- +Triggers
CREATE OR REPLACE FUNCTION set_updated_at_users()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_users_trigger
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_users();
-- +Triggers

-- DROP TRIGGER IF EXISTS set_updated_at_users ON users;
-- DROP FUNCTION IF EXISTS set_updated_at_users();

-- DROP TABLE IF EXISTS users;