#!/bin/bash

############################################
# Этот bash-скрипт предназначен для подготовки
# кода к deploy, а именно проверяет размер файлов
# заменяет локальные данные на внешний IP
############################################

set -e

# COLORS
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

HOME="$(git rev-parse --show-toplevel)"
FILE_GO_HTTP="cmd/server/main.go"

cd "$HOME"
# Используем sed для замены 'Load()' на 'Load(".env.production")'
echo -e "${BLUE}Замена Load() на Load(".env.production")${NC}"
if sed -i.bak 's/godotenv.Load()/godotenv.Load(".env.production")/' "$HOME/$FILE_GO_HTTP"; then
    echo -e "Значение переменной Load() заменено на Load(".env.production") в $FILE_GO_HTTP"
else
    echo -e "Ошибка: Не удалось заменить значение в файле $FILE_GO_HTTP."
    exit 1
fi