#!/bin/bash

############################################
# Этот bash-скрипт предназначен для подготовки
# кода к deploy, а именно проверяет размер файлов
# заменяет локальные данные на внешний IP
############################################

set -e

# COLORS
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

HOME="$(git rev-parse --show-toplevel)"
FILE_C="src/main.c"

cd "$HOME"
echo -e "${BLUE}Замена env_init(\".env\") на env_init(\".env.production\")${NC}"
if sed -i.bak 's/env_init("\.env")/env_init(".env.production")/' "$FILE_C"; then
    echo -e "Значение переменной env_init() заменено на env_init(\".env.production\") в $FILE_C"
else
    echo -e "Ошибка: Не удалось заменить значение в файле $FILE_C."
    exit 1
fi